# ~/.tmuxinator/dev.yml

name: dev
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
#startup_window: vim

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t infographics

windows:
  - src:
      root: ~/src
      layout: even-horizontal
      panes:
        -
        -
  - dotfiles:
      root: ~/.dotfiles
      layout: 3bd2,318x80,0,0{177x80,0,0,1,140x80,178,0,9}
      panes:
        - et .
        -
  - sso-server:
      root: ~/src/sso_server
      layout: e1c2,318x80,0,0{180x80,0,0,2,137x80,181,0[137x39,181,0,10,137x40,181,40,11]}
      panes:
        - et .
        - foreman start
        - 
  - infra:
      layout: tiled
      panes:
        - cd ~/src/identity-infrastructure
        - cd ~/src/sso_server/infrastructure
        - cd ~/src/area51-infrastructure
        - cd ~/src/identity-ansible
  - area51:
      layout: e1c2,318x80,0,0{180x80,0,0,2,137x80,181,0[137x39,181,0,10,137x40,181,40,11]}
      panes:
        - cd ~/src/area51-server; et .
        - cd ~/src/area51-infrastructure
        - cd ~/src/area51-server
